### ISSUE TITLE
copyrightの更新

### ISSUE THREAD

**Issue by Cj-bc** [Y-modify/website#1]
現段階だと2017となっているので、2018にした方がいいのではないかなと思ったという感じ。

**Comment by coord-e** [comment]
した
Thanks

**Comment by coord-e** [comment]
あっ更新したの Y-modify/y-modify.org の方だけどよかったよね

**Comment by Cj-bc** [comment]
ん、あごめんwebsiteってかいてあったからここかと思った…orz
変わってるので大丈夫です
